-- ============================================
-- ১. Admins টেবিল
-- ============================================
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    phone TEXT,
    role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin', 'moderator')),
    is_active BOOLEAN DEFAULT TRUE,
    added_by UUID REFERENCES auth.users(id),
    notes TEXT,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- RLS সক্রিয়
-- ============================================
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- ============================================
-- Super Admin & Admin SELECT
-- ============================================
CREATE POLICY "Admins can view admins" ON admins 
    FOR SELECT TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin'));

-- ============================================
-- Super Admin INSERT
-- ============================================
CREATE POLICY "Super admin insert admins" ON admins 
    FOR INSERT TO authenticated 
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin');

-- ============================================
-- Super Admin UPDATE
-- ============================================
CREATE POLICY "Super admin update admins" ON admins 
    FOR UPDATE TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin') 
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin');

-- ============================================
-- Super Admin DELETE
-- ============================================
CREATE POLICY "Super admin delete admins" ON admins 
    FOR DELETE TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin');

-- ============================================
-- ২. অ্যাডমিন যোগ করার ফাংশন
-- ============================================
CREATE OR REPLACE FUNCTION add_admin(
    p_email TEXT,
    p_full_name TEXT,
    p_phone TEXT DEFAULT NULL,
    p_role TEXT DEFAULT 'admin',
    p_notes TEXT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_added_by UUID;
BEGIN
    IF (auth.jwt() -> 'app_metadata' ->> 'role') != 'super_admin' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Only Super Admin can add admins');
    END IF;
    
    SELECT id INTO v_user_id FROM auth.users WHERE email = p_email;
    
    IF v_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'User not found. Please sign up first.');
    END IF;
    
    v_added_by := auth.uid();
    
    UPDATE auth.users 
    SET raw_app_meta_data = jsonb_build_object('role', p_role, 'provider', 'email')
    WHERE id = v_user_id;
    
    INSERT INTO admins (user_id, email, full_name, phone, role, added_by, notes)
    VALUES (v_user_id, p_email, p_full_name, p_phone, p_role, v_added_by, p_notes)
    ON CONFLICT (user_id) DO UPDATE SET
        role = p_role,
        is_active = TRUE,
        updated_at = NOW();
    
    RETURN jsonb_build_object('success', true, 'message', 'Admin added successfully', 'email', p_email);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- ৩. অ্যাডমিন রিমুভ করার ফাংশন
-- ============================================
CREATE OR REPLACE FUNCTION remove_admin(p_admin_id BIGINT) RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
BEGIN
    IF (auth.jwt() -> 'app_metadata' ->> 'role') != 'super_admin' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Only Super Admin can remove admins');
    END IF;
    
    SELECT user_id INTO v_user_id FROM admins WHERE id = p_admin_id;
    
    IF v_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Admin not found');
    END IF;
    
    UPDATE auth.users 
    SET raw_app_meta_data = raw_app_meta_data - 'role'
    WHERE id = v_user_id;
    
    UPDATE admins SET is_active = FALSE, updated_at = NOW() WHERE id = p_admin_id;
    
    RETURN jsonb_build_object('success', true, 'message', 'Admin removed successfully');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- ৪. অ্যাডমিন আপডেট ফাংশন
-- ============================================
CREATE OR REPLACE FUNCTION update_admin(
    p_admin_id BIGINT,
    p_role TEXT DEFAULT NULL,
    p_is_active BOOLEAN DEFAULT NULL,
    p_notes TEXT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
BEGIN
    IF (auth.jwt() -> 'app_metadata' ->> 'role') != 'super_admin' THEN
        RETURN jsonb_build_object('success', false, 'message', 'Only Super Admin can update admins');
    END IF;
    
    SELECT user_id INTO v_user_id FROM admins WHERE id = p_admin_id;
    
    IF v_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Admin not found');
    END IF;
    
    UPDATE admins SET
        role = COALESCE(p_role, role),
        is_active = COALESCE(p_is_active, is_active),
        notes = COALESCE(p_notes, notes),
        updated_at = NOW()
    WHERE id = p_admin_id;
    
    IF p_role IS NOT NULL THEN
        UPDATE auth.users 
        SET raw_app_meta_data = jsonb_set(raw_app_meta_data, '{role}', to_jsonb(p_role))
        WHERE id = v_user_id;
    END IF;
    
    RETURN jsonb_build_object('success', true, 'message', 'Admin updated successfully');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- ৫. প্রথম Super Admin সেটআপ
-- ============================================
INSERT INTO admins (user_id, email, full_name, role)
VALUES (
    'afab66e1-af48-406e-a018-20ac68ec2286',
    (SELECT email FROM auth.users WHERE id = 'afab66e1-af48-406e-a018-20ac68ec2286'),
    'Super Admin',
    'super_admin'
)
ON CONFLICT (user_id) DO UPDATE SET
    role = 'super_admin',
    updated_at = NOW();

UPDATE auth.users 
SET raw_app_meta_data = jsonb_build_object('role', 'super_admin', 'provider', 'email')
WHERE id = 'afab66e1-af48-406e-a018-20ac68ec2286';

-- ============================================
-- ইনডেক্স
-- ============================================
CREATE INDEX IF NOT EXISTS idx_admins_user ON admins(user_id);
CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email);
CREATE INDEX IF NOT EXISTS idx_admins_role ON admins(role);
CREATE INDEX IF NOT EXISTS idx_admins_active ON admins(is_active);
